---
- hosts: dbservers
  remote_user: ansible
  become: yes
 
  tasks:
    - name: install repo for PostgreSQL 9.6
      yum:
        name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-6-x86_64/pgdg-centos94-9.6-3.noarch.rpm
        state: present
 
    - name: install repo for PostgreSQL 10
      yum:
        name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-6-x86_64/pgdg-centos96-10-3.noarch.rpm
        state: present
...
