---
- hosts: "{{ host }}"
  remote_user: postgres

  tasks:
    - name: crate dir for st3simple config files
      file: path=~/st3simple/{{item}} state=directory mode=0755
      with_items:
        - "log"
        - "pid"
...

