---
- hosts: "{{ slave }}"
  remote_user: ansible
  become: yes
 
  tasks:
    - systemd:
        name: postgresql-9.6
        state: stopped
 
    - systemd:
        name: postgresql-10
        state: stopped
 
    - file:
       path: /var/lib/pgsql/10/data/
       state: absent
 
    - file:
       path:  /var/lib/pgsql/10/data/
       owner: postgres
       group: postgres
       mode:  0700
       state: directory
 
- hosts: "{{ slave }}"
  remote_user: postgres
 
  tasks:
    - name: execute base backup
      shell: |
        export PGPASSWORD="{{ passwd }}" && \
        /usr/pgsql-10/bin/pg_basebackup \
            -h {{ master }} \
            -U replicant \
            -D /var/lib/pgsql/10/data \
            -P -v --wal-method=stream 2>&1
 
        exit 0
 
    - name: add new configuration "recovery.conf"
      blockinfile:
        create: yes
        dest: /var/lib/pgsql/10/data/recovery.conf
        block: |
          standby_mode = 'on'
          primary_conninfo = 'user=replicant password={{ passwd }} host={{ master }} port=5432 sslmode=prefer'
          recovery_target_timeline = 'latest'
 
    - name: update environment variables in UNIX account postgres
      blockinfile:
        create: yes
        dest: /var/lib/pgsql/.pgsql_profile
        block: |
          export PGHOST=/tmp PAGER=less PGDATA=/var/lib/pgsql/10/data
 
- hosts: "{{ slave }}"
  remote_user: ansible
  become: yes
 
  tasks:
    - service:
        name: postgresql-10
        state: started
...
